production:
#    hostname: localhost6
  solr:
    hostname: localhost
    port: 8986
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8985
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8984
    log_level: WARNING
    

#	running on localhost6 in production seems to work as opposed to just localhost
#	actually, it doesn't seem to make any difference as noted yet.
#	Once started as tomcat, it seems best to logout, otherwise it hangs
#	Perhaps adding a NOHUP or something would fix this.
